version: '3'
services:
  web:
    image: node:14
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: "npm run start"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

